package com.a4a.testvalidateforminputs

enum class FormElement {
    CLIENT_OR_ISSUER_NAME,
    CLIENT_OR_ISSUER_FIRST_NAME,
    CLIENT_OR_ISSUER_EMAIL,
    CLIENT_OR_ISSUER_ADDRESS1,
    CLIENT_OR_ISSUER_ADDRESS2,
    CLIENT_OR_ISSUER_ZIP,
    CLIENT_OR_ISSUER_CITY,
    CLIENT_OR_ISSUER_PHONE,
    CLIENT_OR_ISSUER_NOTES,
    CLIENT_OR_ISSUER_IDENTIFICATION1,
    CLIENT_OR_ISSUER_IDENTIFICATION1_LABEL,
    CLIENT_OR_ISSUER_IDENTIFICATION1_VALUE,
    CLIENT_OR_ISSUER_IDENTIFICATION2,
    CLIENT_OR_ISSUER_IDENTIFICATION2_LABEL,
    CLIENT_OR_ISSUER_IDENTIFICATION2_VALUE,
    SUBMIT_BUTTON
}